fileVersion: 1
id: "25"
mappingDefinitions:
  CLAIMS:
    database: INSURANCE_CURATED
    schema: CLAIMS
  COMMON:
    database: INSURANCE_CURATED
    schema: COMMON
  DASHBOARDS:
    database: INSURANCE_ANALYTICS
    schema: DASHBOARDS
  SRC:
    database: placeholder
    schema: placeholder
  SRC_INSURANCE_SQL_SERVER:
    database: FINSERV_INSURANCE_UNDERWRITING
    schema: insurance_db
  UNDERWRITING:
    database: INSURANCE_CURATED
    schema: UNDERWRITING
  WORK:
    database: JJ_PROD
    schema: JJ_PROD_SCHEMA
name: Production
type: Environment
