fileVersion: 1
id: "25"
mappingDefinitions:
  BRONZE:
    database: ""
    schema: ""
  GOLD:
    database: ""
    schema: ""
  SAMPLE:
    database: ""
    schema: ""
  SILVER:
    database: ""
    schema: ""
  SRC_JJ_DEV:
    database: ""
    schema: ""
name: Production
type: Environment
