fileVersion: 1
id: "25"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: TXM_DEMO_DW_DB_PROD
    schema: TXM_DEMO_DW_SCHEMA_PROD
name: Production
type: Environment
