fileVersion: 1
id: "25"
mappingDefinitions:
  CLAIMS:
    database: ""
    schema: ""
  COMMON:
    database: ""
    schema: ""
  DASHBOARDS:
    database: ""
    schema: ""
  SRC:
    database: ""
    schema: ""
  SRC_INSURANCE_SQL_SERVER:
    database: ""
    schema: ""
  UNDERWRITING:
    database: ""
    schema: ""
  WORK:
    database: TXM_DEMO_DW_DB_PROD
    schema: TXM_DEMO_DW_SCHEMA_PROD
name: Production
type: Environment
