fileVersion: 1
id: "25"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: JJ_PROD
    schema: JJ_PROD_SCHEMA
name: Production
type: Environment
